from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .item.tags_item_request_builder import TagsItemRequestBuilder
    from .tags_get_response import TagsGetResponse

class TagsRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /tags
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new TagsRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/tags{?page*,page_size*}", path_parameters)
    
    def by_id(self,id: int) -> TagsItemRequestBuilder:
        """
        Gets an item from the rawg_kiota_client.tags.item collection
        param id: A unique integer value identifying this Tag.
        Returns: TagsItemRequestBuilder
        """
        if id is None:
            raise TypeError("id cannot be null.")
        from .item.tags_item_request_builder import TagsItemRequestBuilder

        url_tpl_params = get_path_parameters(self.path_parameters)
        url_tpl_params["id"] = id
        return TagsItemRequestBuilder(self.request_adapter, url_tpl_params)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[TagsRequestBuilderGetQueryParameters]] = None) -> Optional[TagsGetResponse]:
        """
        Get a list of tags.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[TagsGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .tags_get_response import TagsGetResponse

        return await self.request_adapter.send_async(request_info, TagsGetResponse, None)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[TagsRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> TagsRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: TagsRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return TagsRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class TagsRequestBuilderGetQueryParameters():
        """
        Get a list of tags.
        """
        # A page number within the paginated result set.
        page: Optional[int] = None

        # Number of results to return per page.
        page_size: Optional[int] = None

    
    @dataclass
    class TagsRequestBuilderGetRequestConfiguration(RequestConfiguration[TagsRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

