from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .development_team_get_response import DevelopmentTeamGetResponse

class DevelopmentTeamRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /games/{game_pk-id}/development-team
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new DevelopmentTeamRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/games/{game_pk%2Did}/development-team{?ordering*,page*,page_size*}", path_parameters)
    
    async def get(self,request_configuration: Optional[RequestConfiguration[DevelopmentTeamRequestBuilderGetQueryParameters]] = None) -> Optional[DevelopmentTeamGetResponse]:
        """
        Get a list of individual creators that were part of the development team.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[DevelopmentTeamGetResponse]
        """
        request_info = self.to_get_request_information(
            request_configuration
        )
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .development_team_get_response import DevelopmentTeamGetResponse

        return await self.request_adapter.send_async(request_info, DevelopmentTeamGetResponse, None)
    
    def to_get_request_information(self,request_configuration: Optional[RequestConfiguration[DevelopmentTeamRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> DevelopmentTeamRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: DevelopmentTeamRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return DevelopmentTeamRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class DevelopmentTeamRequestBuilderGetQueryParameters():
        """
        Get a list of individual creators that were part of the development team.
        """
        # Which field to use when ordering the results.
        ordering: Optional[str] = None

        # A page number within the paginated result set.
        page: Optional[int] = None

        # Number of results to return per page.
        page_size: Optional[int] = None

    
    @dataclass
    class DevelopmentTeamRequestBuilderGetRequestConfiguration(RequestConfiguration[DevelopmentTeamRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

